wine.ds <- read.csv2("winequality-white.csv", header=TRUE, sep = ";", dec =".")
str(wine.ds)
colMeans(wine.ds)
quants <- c(0.25,0.50,0.75)
apply(wine.ds , 2 , quantile , probs = quants , na.rm = TRUE)
apply(wine.ds, 2, FUN = IQR)
apply(wine.ds, 2, FUN = var)
apply(wine.ds, 2, FUN = sd)
install.packages("e1071")
library(e1071)
apply(wine.ds, 2, FUN = skewness)
apply(wine.ds, 2, FUN = kurtosis)
wine.stats <- data.frame(matrix(ncol = 12, nrow = 9))
x <- c("Ustalona_kwasowosc", "Lotna_kwasowosc", "Kwas cytrynowy", "Cukier", "Chlorki", "Lotny_SO2", "Calkowity_SO2", "Gestosc", "pH","Siarczany", "Alkohol", "Jakosc")
colnames(wine.stats) <- x
y <- c("Srednia", "Q1", "Q2", "Q3", "IQR", "Wariancja", "Odchylenie standardowe", "Skosnosc", "Kurtoza")
rownames(wine.stats) <- y
wine.stats[1,] <- colMeans(wine.ds)
wine.stats[2,] <- apply(wine.ds , 2 , quantile , probs = 0.25 , na.rm = TRUE)
wine.stats[3,] <- apply(wine.ds , 2 , quantile , probs = 0.5 , na.rm = TRUE)
wine.stats[4,] <- apply(wine.ds , 2 , quantile , probs = 0.75 , na.rm = TRUE)
wine.stats[5,] <- apply(wine.ds, 2, FUN = IQR)
wine.stats[6,] <- apply(wine.ds, 2, FUN = var)
wine.stats[7,] <- apply(wine.ds, 2, FUN = sd)
wine.stats[8,] <- apply(wine.ds, 2, FUN = skewness)
wine.stats[9,] <- apply(wine.ds, 2, FUN = kurtosis)

summary(wine.ds)
head(wine.ds)
pairs(wine.ds, col = wine.ds$quality)

wine39 = subset(wine.ds, subset=(wine.ds$quality == "3" | wine.ds$quality == "9"))
pairs(wine39, col = wine39$quality)

boxplot(wine.ds$fixed.acidity ~ wine.ds$quality)
boxplot(wine.ds$volatile.acidity ~ wine.ds$quality)
boxplot(wine.ds$citric.acid ~ wine.ds$quality)
boxplot(wine.ds$residual.sugar ~ wine.ds$quality)
boxplot(wine.ds$chlorides ~ wine.ds$quality)
boxplot(wine.ds$free.sulfur.dioxide ~ wine.ds$quality)
boxplot(wine.ds$total.sulfur.dioxide ~ wine.ds$quality)
boxplot(wine.ds$density ~ wine.ds$quality)
boxplot(wine.ds$pH ~ wine.ds$quality)
boxplot(wine.ds$sulphates ~ wine.ds$quality)
boxplot(wine.ds$alcohol ~ wine.ds$quality)

